#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bokeh
Version  : 0.12.5
Release  : 4
URL      : http://pypi.debian.net/bokeh/bokeh-0.12.5.tar.gz
Source0  : http://pypi.debian.net/bokeh/bokeh-0.12.5.tar.gz
Summary  : Interactive plots and applications in the browser from Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: bokeh-bin
Requires: bokeh-python
Requires: Jinja2
Requires: PyYAML
Requires: numpy
Requires: python-dateutil
Requires: requests
Requires: six
Requires: tornado
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
# Bokeh Examples
## Examples in this repository
This directory contains many examples of different ways to use Bokeh. As Bokeh has been evolving
fast, it is important that you **ensure that the version of an example you're looking at matches
the version of Bokeh you are running**.

%package bin
Summary: bin components for the bokeh package.
Group: Binaries

%description bin
bin components for the bokeh package.


%package python
Summary: python components for the bokeh package.
Group: Default

%description python
python components for the bokeh package.


%prep
%setup -q -n bokeh-0.12.5

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492292301
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492292301
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bokeh

%files python
%defattr(-,root,root,-)
%exclude /usr/lib/python2.7/site-packages/tests/__init__.py
%exclude /usr/lib/python2.7/site-packages/tests/__init__.pyc
%exclude /usr/lib/python2.7/site-packages/tests/conftest.py
%exclude /usr/lib/python2.7/site-packages/tests/conftest.pyc
%exclude /usr/lib/python3.6/site-packages/tests/__init__.py
%exclude /usr/lib/python3.6/site-packages/tests/__pycache__/__init__.cpython-36.pyc
%exclude /usr/lib/python3.6/site-packages/tests/__pycache__/conftest.cpython-36.pyc
%exclude /usr/lib/python3.6/site-packages/tests/conftest.py
/usr/lib/python2*/*
/usr/lib/python3*/*
